### ISSUE TITLE
OSError: Can't load weights for model

### ISSUE THREAD

**Issue by olha-kaminska** [cardiffnlp/tweeteval#1]
Hello. I tried to run the samples but got an error in this part:

`task='emotion'`
`MODEL = f"cardiffnlp/twitter-roberta-base-{task}"`
`tokenizer = AutoTokenizer.from_pretrained(MODEL)`
`model = AutoModelForSequenceClassification.from_pretrained(MODEL) `<-- here is an error

An error:

> OSError: Can't load weights for 'cardiffnlp/twitter-roberta-base-emotion'. Make sure that:
> - 'cardiffnlp/twitter-roberta-base-emotion' is a correct model identifier listed on 'https://huggingface.co/models'
> - or 'cardiffnlp/twitter-roberta-base-emotion' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.

It was the same for just 'twitter-roberta-base'. What could be wrong here? 
Thanks!

**Comment by luisespinosaanke** [comment]
Hi, thanks for asking! Did you try that in the colab notebook [here](https://colab.research.google.com/drive/18cNn4cJ-bAi-Luiqi8V6c09Tj-iiX0oG?authuser=2)? This issue could be due to an older version of the `transformers` library.

**Comment by olha-kaminska** [comment]
Hi! Thanks for the comment, but package update didn't help me much. 

The solution for me was to clone the model repo, as it described [here](https://huggingface.co/cardiffnlp/twitter-roberta-base-emotion/tree/main#how-to-use) :

`git lfs install`
`git clone https://huggingface.co/cardiffnlp/twitter-roberta-base-emotion`

Then I used uploaded model like that:

`model = AutoModelForSequenceClassification.from_pretrained(r"C:\Users\...\site-packages\transformers\twitter-roberta-base-emotion", from_tf=True)`

So now it is working :)

**Comment by ioana-blue** [comment]
I get the same problem with loading the model with some existing code. It's weird, it does find the path of the model, it downloads some of the files there (e.g., vocab.json, config.json, merges.txt, etc.) but not the pytorch_model.bin file. 

I'm using transformers 3.4. Any suggestions? I use models from the model hub all the time (I just reran a plain bert to make sure that the recent update of the hub didn't break some things in my older code). 

I'd rather not download the files locally. Defeats the whole point of the model hub. 

Thanks!

**Comment by VicD1999** [comment]
Hello, 
I just remove the /cardiffnlp directory with rm linux command in a cell before I run the code and it works. 
Not very elegant but it works.

**Comment by vladradishevsky** [comment]
First, remove the cardiffnlp folder via `rm -r ./cardiffnlp`

After that, you can save pretrained weights using this code

```
task='sentiment'
MODEL = f"cardiffnlp/twitter-roberta-base-{task}"

tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)
    
tokenizer.save_pretrained(MODEL)
model.save_pretrained(MODEL) 
```

**Comment by suntea233** [comment]
i met the same problem in "xlm-roberta-base".
but i cannot find which file i should delete.
is there any other methods to solve this kind of problems

**Comment by bwang514** [comment]
Removing this line helps. 

> model.save_pretrained(MODEL)
