### ISSUE TITLE
Possible privacy leak

### ISSUE THREAD

**Issue by chrisfalter** [cardiffnlp/tweeteval#7]
As noted in issue #5, many valid user handles are present in the sentiment dataset. To the extent that this can be considered a privacy leak or violation of the Twitter Developer Agreement, it needs to be addressed.

Simply merging my PR would not suffice because the valid user handles could be reconstructed from file history.

If you need to put the genie back in the bottle, you may be able to delete the history for the affected files, but if not, you might have to rebuild the repo. Not being a true git wizard, I cannot make a recommendation without further background research, for which I unfortunately do not have the time at the moment. :/

**Comment by pedrada88** [comment]
Thanks again! This has now been corrected as well (see comment in issue #5) and history for those specific instances should be removed soon as well.
